# vitis.pyi - stub for IDE autocomplete

class Workspace:
    def __init__(self, path: str): ...
    def createPlatform(self, name: str): ...
    
class Platform:
    def createHardwareSpec(self, xsa_path: str): ...
    def createDomain(self, name: str, os: str, proc: str): ...
    def setDefaultDomain(self, domain): ...
    def setSysConfigDefaultProcessor(self, name: str): ...
    def build(self): ...
    def export(self): ...
    def getPath(self) -> str: ...